[package]
name = "lyapunov-demo"
version = "0.1.0"
edition = "2021"
authors = ["Lasse <lassekau@proton.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miniquad = "0.3.15"
quad-rand = "0.2.1"
